### ISSUE TITLE
Label the Binomial Distribution graph.

### ISSUE THREAD

**Issue by Krazete** [Krazete/takatomon#1]
Almost none of the interactive graphics on [my Common Distributions page](https://krazete.github.io/distribution/distributions.html) work the way I want it to, but let's just focus on one of the good ones.

The Binomial Distribution graph needs labels (and axes probably).
- The height of each bar is the probability p.
- The number of bars is n.
- The thin tall line is the expectation E[X].
- The thin short lines to either side of the thin tall line represents variance Var(X).

Here's [the main file you want to change](https://github.com/Krazete/krazete.github.io/blob/master/distribution/distributions.js) (lines 45-62).
Though you might also want to increase the canvas size in [this file](https://github.com/Krazete/krazete.github.io/blob/master/distribution/distributions.html) (line 50) to make room for labels.

**Comment by adityatandon007** [comment]
@Krazete would like to try this out

**Comment by Krazete** [comment]
@adityatandon007 👍  Go for it.

**Comment by Krazete** [comment]
File no longer exists.
